language: python
python:
- "3.7"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install codecov

# command to run tests
script:
- nose2

after_success:
- codecov