"""add done column

Revision ID: b30180f99475
Revises: 6c7cca207095
Create Date: 2019-09-28 00:27:42.724259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30180f99475'
down_revision = '6c7cca207095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done')
    # ### end Alembic commands ###
